version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - POSTGRES_PRISMA_URL=postgresql://seed-e-user:${POSTGRES_PASSWORD}@postgres:5432/seed-e-db
      - POSTGRES_URL_NON_POOLING=postgresql://seed-e-user:${POSTGRES_PASSWORD}@postgres:5432/seed-e-db
      - XPUB_HASH_SECRET=${XPUB_HASH_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - LND_REST_URL=${LND_REST_URL:-}
      - LND_INVOICE_MACAROON=${LND_INVOICE_MACAROON:-}
    depends_on:
      - postgres
    restart: always
    command: sh -c "npx prisma generate && npm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=seed-e-user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-seed-e-password}
      - POSTGRES_DB=seed-e-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seed-e-user -d seed-e-db"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
