version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - POSTGRES_PRISMA_URL=postgresql://seed-e-user:${POSTGRES_PASSWORD}@postgres:5432/seed-e-db
      - POSTGRES_URL_NON_POOLING=postgresql://seed-e-user:${POSTGRES_PASSWORD}@postgres:5432/seed-e-db
      - XPUB_HASH_SECRET=${XPUB_HASH_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
      - LND_REST_URL=
      - LND_INVOICE_MACAROON=
    depends_on:
      - postgres
    restart: always
    command: sh -c "npx prisma migrate deploy && npm start"
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=seed-e-user
      - POSTGRES_PASSWORD=seed-e-password
      - POSTGRES_DB=seed-e-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
