name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Seed-E Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/seed-e/Seed-E
            git pull origin main

            # Create .env file with GitHub secrets
            cat > .env << EOF
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            XPUB_HASH_SECRET=${{ secrets.XPUB_HASH_SECRET }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            LND_REST_URL=${{ secrets.LND_REST_URL }}
            LND_INVOICE_MACAROON=${{ secrets.LND_INVOICE_MACAROON }}
            EOF

            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            docker-compose ps
            echo "Deployment completed successfully!"
